name: statamic-playground
recipe: laravel
config:
  webroot: public
  php: "8.2"
  composer_version: 2
  database: "mysql:8.0"
  cache: none
proxy:
  node:
    - vite.statamic-playground.lndo.site
services:
  node:
    type: node:16
    globals: []
    ssl: false
    command: tail -f /dev/null
tooling:
  node:
    service: node
  npm:
    service: node
  npx:
    service: node
